base_url: http://halfthetruth.de

description: "Just 42/2"
root_desc: "halfthetruth.de"

markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
paginate: 10

exclude:
  - 'bin'
  - 'sass'
  - 'Rakefile'
  - 'config.rb'
