title: halfthetruth.de
base_url: http://halfthetruth.de

description: "Just 42/2"
root_desc: "halfthetruth.de"

markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
paginate: 8

exclude:
  - 'bin'
  - 'sass'
  - 'Rakefile'
  - 'Procfile'
  - 'config.rb'

# Custom
excerpt_link:   "Read More&hellip;"

# Plugins
disqus_shortname:  halfthetruth
category_dir:       categories

index_pages:
  category:
    do_related:     false
    title_prefix:   'Category: '
  tag:
    do_related:     true
    title_prefix:   'Tag: '

authors:
  martinlowinski:
    name: Martin Lowinski
    display_name: Martin Lowinski
    gravatar: cc9aeac10a3de847d39e6c09ea364c1e
    web: http://martinlowinski.de
    twitter: c0b0lt
    github: martinlowinski
