title: "halfthetruth.de"
description: "Martin Lowinski's personal blog"
baseurl: "/"
author: Martin Lowinski
url: "https://halfthetruth.de"

permalink: pretty
collections_dir: collections
markdown: kramdown
highlighter: rouge

logo:
  logo_desktop_text: "halfthetruth.de"
  logo_mobile_text: "halfthetruth.de"

seo:
  meta_twitter_site: "@molowinski"
  meta_twitter_creator: "@molowinski"

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-paginate

paginate: 5
paginate_path: /posts/page:num/

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      layout: category
      permalink: /category/:basename/

postcss:
  cache: false

brotli:
  quality: 9
  extensions:
    - '.html'
    - '.js'
    - '.css'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
