base_url: http://halfthetruth.de

description: "Just 42/2"
root_desc: "halfthetruth.de"

markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title

exclude: ['sass/*', 'Rakefile', 'config.rb']
