title: halfthetruth.de
base_url: http://halfthetruth.de

description: "Just 42/2"
root_desc: "halfthetruth.de"

markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
paginate: 10

exclude:
  - 'bin'
  - 'sass'
  - 'Rakefile'
  - 'config.rb'

# Plugins
disqus_shortname:  halfthetruth
category_dir:       categories

index_pages:
  category:
    do_related:     false
    title_prefix:   'Category: '
